import { Card, EmptyState, PageHeader, ProcessingState, StatusBadge, Tabs } from '@/Components/UI';
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import type { Evidence, Finding, Paper, Reference, Review, Score } from '@/types';
import { displayDate } from '@/lib/contracts';
import { Head, Link, router, useForm } from '@inertiajs/react';
import { Download, ExternalLink, MessageSquareText, Pencil, Send, Trash2 } from 'lucide-react';
import { FormEvent, useState } from 'react';
const tabs=[['overview','Overview'],['analysis','Analysis'],['scores','Scores'],['findings','Findings'],['references','References'],['reviewer','AI Reviewer'],['qa','Q&A'],['reviews','Reviews']].map(([id,label])=>({id,label}));
type Props={paper:Paper;tab?:string;analysis?:Record<string,unknown>|null;scores?:Score[];findings?:Finding[];references?:Reference[];aiReview?:Review|null;reviews?:Review[];reviewers?:Array<{id:number;name:string}>;questions?:Array<{id?:number;question:string;answer?:string|null;found?:boolean;evidence?:Evidence[]}>;can?:{download?:boolean;update?:boolean;delete?:boolean;review?:boolean;ask?:boolean;retry?:boolean}};
export default function Show(p:Props){const active=p.tab??new URLSearchParams(window.location.search).get('tab')??'overview';const deletePaper=()=>{if(window.confirm('Delete this paper and its private PDF? This cannot be undone.'))router.delete(`/papers/${p.paper.id}`)};
const triggerAiReview=()=>{if(window.confirm('Request a new AI Review?'))router.post(`/papers/${p.paper.id}/ai-review`)};
return <AuthenticatedLayout><Head title={p.paper.title}/><div className="page-wrap"><PageHeader eyebrow="Paper workspace" title={p.paper.title} description={[p.paper.authors?.map(a=>a.name).join(', '),p.paper.journal,p.paper.publication_year].filter(Boolean).join(' · ')||'Publication metadata not provided'} actions={<>{p.can?.update===true&&<button onClick={triggerAiReview} className="btn-secondary">Trigger AI Review</button>}{p.can?.download===true&&<a href={`/papers/${p.paper.id}/export`} className="btn-secondary">📄 Export Report</a>}{p.can?.download===true&&<a href={`/papers/${p.paper.id}/download`} className="btn-secondary"><Download className="h-4 w-4"/>PDF</a>}{p.can?.update===true&&<Link href={`/papers/${p.paper.id}/edit`} className="btn-secondary"><Pencil className="h-4 w-4"/>Edit</Link>}{p.can?.delete===true&&<button type="button" onClick={deletePaper} className="btn-secondary text-rose-700"><Trash2 className="h-4 w-4"/>Delete paper</button>}<StatusBadge status={p.paper.status}/></>}/><ProcessingState status={p.paper.status} error={p.paper.error_message}/><div className="mt-6"><Tabs items={tabs} active={active} baseUrl={`/papers/${p.paper.id}`}/>{active==='overview'&&<Overview {...p}/>} {active==='analysis'&&<Analysis value={p.analysis}/>} {active==='scores'&&<Scores rows={p.scores}/>} {active==='findings'&&<Findings rows={p.findings}/>} {active==='references'&&<References rows={p.references}/>} {active==='reviewer'&&<ReviewView review={p.aiReview}/>} {active==='qa'&&<Qa {...p}/>} {active==='reviews'&&<Reviews {...p}/>}</div></div></AuthenticatedLayout>}
function Overview({paper,analysis}:{paper:Paper;analysis?:Record<string,unknown>|null}){return <div className="grid gap-6 lg:grid-cols-[1.5fr_.5fr]"><Card className="p-6"><h2 className="text-lg font-semibold">Abstract</h2><p className="mt-3 whitespace-pre-line text-sm leading-7 text-slate-600">{paper.abstract||'No abstract was provided.'}</p></Card><Card className="p-6"><h2 className="font-semibold">Metadata</h2><dl className="mt-4 space-y-4 text-sm"><Meta k="DOI" v={paper.doi}/><Meta k="Journal" v={paper.journal}/><Meta k="Year" v={paper.publication_year}/><Meta k="Uploaded" v={displayDate(paper.created_at)}/><Meta k="Domain" v={String(analysis?.research_domain??'—')}/></dl></Card></div>}
function Meta({k,v}:{k:string;v:unknown}){return <div><dt className="text-xs font-semibold uppercase tracking-wide text-slate-400">{k}</dt><dd className="mt-1 break-words text-slate-700">{v==null||v===''?'—':String(v)}</dd></div>}
function Analysis({value}:{value?:Record<string,unknown>|null}){if(!value)return <BoxEmpty what="analysis"/>;const entries=Object.entries(value).filter(([,v])=>v!=null);return <div className="grid gap-4 md:grid-cols-2">{entries.map(([k,v])=><Card key={k} className="p-5"><h3 className="font-semibold capitalize">{k.replaceAll('_',' ')}</h3><div className="mt-3 text-sm leading-6 text-slate-600">{render(v)}</div></Card>)}</div>}
const render=(v:unknown):React.ReactNode=>Array.isArray(v)?<ul className="list-disc space-y-1 pl-5">{v.map((x,i)=><li key={i}>{typeof x==='object'?JSON.stringify(x):String(x)}</li>)}</ul>:typeof v==='object'?<dl className="space-y-2">{Object.entries(v as Record<string,unknown>).map(([k,x])=><div key={k}><dt className="font-medium capitalize text-slate-800">{k.replaceAll('_',' ')}</dt><dd>{Array.isArray(x)?x.join(', '):String(x??'—')}</dd></div>)}</dl>:String(v);
function Scores({rows=[]}:{rows?:Score[]}){return rows.length?<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{rows.map((s,i)=><Card key={s.id??i} className="p-5"><div className="flex justify-between"><h3 className="font-semibold capitalize">{s.criterion.replaceAll('_',' ')}</h3><strong className="text-2xl text-teal-700">{s.score}<span className="text-sm text-slate-400">/100</span></strong></div><div className="mt-3 h-2 rounded bg-slate-100"><div className="h-2 rounded bg-teal-600" style={{width:`${Math.min(100,Math.max(0,s.score))}%`}}/></div><p className="mt-4 text-sm leading-6 text-slate-600">{s.reason||'No scoring rationale returned.'}</p></Card>)}</div>:<BoxEmpty what="scores"/>}
function Findings({rows=[]}:{rows?:Finding[]}){return rows.length?<div className="space-y-4">{rows.map((f,i)=><Card key={f.id??i} className="p-5"><div className="flex flex-wrap items-center gap-2"><span className={`status ${['high','critical'].includes(f.severity?.toLowerCase()??'')?'status-danger':'status-warning'}`}>{f.severity||'Unrated'}</span><span className="text-xs font-semibold uppercase text-slate-400">{f.category}</span></div><h3 className="mt-3 font-semibold">{f.finding||f.title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{f.explanation}</p><EvidenceList rows={f.evidence}/></Card>)}</div>:<BoxEmpty what="findings"/>}
function References({rows=[]}:{rows?:Reference[]}){return rows.length?<Card className="divide-y divide-slate-100">{rows.map((r,i)=><div className="p-5" key={r.id??i}><p className="text-sm leading-6">{r.citation||[r.authors,r.title,r.year].filter(Boolean).join('. ')}</p>{r.cited_in_text!=null&&<p className="mt-2 text-xs text-slate-500">{r.cited_in_text?'Observed in text':'Not observed in text'}</p>}</div>)}</Card>:<BoxEmpty what="references"/>}
function ReviewView({review}:{review?:Review|null}){return review?<div className="space-y-4"><Card className="p-6"><div className="flex flex-wrap justify-between gap-3"><h2 className="text-lg font-semibold">Reviewer report</h2><span className="status status-info">{review.recommendation?.replaceAll('_',' ')||'No recommendation'}</span></div><p className="mt-4 text-sm leading-7 text-slate-600">{review.summary}</p></Card>{[['Strengths',review.strengths],['Major concerns',review.major_concerns],['Minor concerns',review.minor_concerns]].map(([title,items])=><Card key={String(title)} className="p-5"><h3 className="font-semibold">{String(title)}</h3>{Array.isArray(items)&&items.length?<ul className="mt-3 list-disc space-y-2 pl-5 text-sm text-slate-600">{items.map((x,i)=><li key={i}>{x}</li>)}</ul>:<p className="mt-2 text-sm text-slate-500">None returned.</p>}</Card>)}</div>:<BoxEmpty what="AI reviewer report"/>}
function Qa(p:Props){const f=useForm({question:''});const submit=(e:FormEvent)=>{e.preventDefault();f.post(`/papers/${p.paper.id}/questions`,{onSuccess:()=>f.reset()})};return <div className="space-y-5"><Card className="p-5"><form onSubmit={submit}><label htmlFor="question" className="font-semibold">Ask about this paper</label><p className="mt-1 text-sm text-slate-500">Answers are grounded only in the selected paper and include evidence when available.</p><div className="mt-4 flex flex-col gap-2 sm:flex-row"><input id="question" required className="field flex-1" value={f.data.question} onChange={e=>f.setData('question',e.target.value)} placeholder="What methodology does the paper use?"/><button disabled={f.processing||!p.can?.ask} className="btn-primary"><Send className="h-4 w-4"/>Ask</button></div>{f.errors.question&&<p className="mt-2 text-sm text-rose-600">{f.errors.question}</p>}</form></Card>{p.questions?.length?p.questions.map((q,i)=><Card key={q.id??i} className="p-5"><p className="font-semibold">{q.question}</p><p className="mt-3 text-sm leading-7 text-slate-600">{q.answer||'Awaiting an answer.'}</p><EvidenceList rows={q.evidence}/></Card>):<BoxEmpty what="questions"/>}</div>}
function Reviews(p:Props){return <div className="space-y-6">{p.reviewers&&p.reviewers.length>0&&<AssignReviewer paperId={p.paper.id} reviewers={p.reviewers}/>}{p.reviews?.length?<div className="space-y-4">{p.reviews.map(r=><ReviewCard key={r.id} review={r} paperId={p.paper.id} />)}</div>:<BoxEmpty what="reviews"/>}</div>}
function AssignReviewer({paperId,reviewers}:{paperId:number;reviewers:Array<{id:number;name:string}>}){const f=useForm({reviewer_id:''});const [recs,setRecs]=useState<Array<{reviewer_id:number;reason:string;confidence_score:number}>|null>(null);const [loadingRecs,setLoadingRecs]=useState(false);const submit=(e:FormEvent)=>{e.preventDefault();f.post(`/papers/${paperId}/assign`,{onSuccess:()=>{f.reset();setRecs(null);}})};
const fetchRecs=async()=>{setLoadingRecs(true);try{const res=await fetch(`/papers/${paperId}/recommendations`);const data=await res.json();if(data.recommendations)setRecs(data.recommendations);}catch(err){console.error(err);}setLoadingRecs(false);};
return <div className="space-y-4"><Card className="p-5 bg-slate-50"><form onSubmit={submit} className="flex gap-4 items-end"><label className="flex-1"><span className="block text-sm font-semibold mb-1">Assign Reviewer</span><select required className="field" value={f.data.reviewer_id} onChange={e=>f.setData('reviewer_id',e.target.value)}><option value="">Select a reviewer...</option>{reviewers.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label><div className="flex gap-2"><button type="button" onClick={fetchRecs} disabled={loadingRecs} className="btn-secondary">✨ AI Recommend</button><button className="btn-primary" disabled={f.processing||!f.data.reviewer_id}>Assign</button></div></form></Card>
{recs&&recs.length>0&&<div className="grid gap-4 md:grid-cols-3">{recs.map(r=>{const rev=reviewers.find(x=>x.id===r.reviewer_id);return <Card key={r.reviewer_id} className="p-4 border-teal-200 bg-teal-50"><h4 className="font-semibold text-teal-900">{rev?.name||'Unknown'}</h4><p className="mt-2 text-xs leading-5 text-teal-800">{r.reason}</p><button type="button" onClick={()=>{f.setData('reviewer_id',String(r.reviewer_id));}} className="mt-4 text-xs font-semibold text-teal-700 hover:text-teal-900">Select this reviewer</button></Card>})}</div>}
{recs&&recs.length===0&&<p className="text-sm text-slate-500">No recommendations found.</p>}</div>}
function ReviewCard({review,paperId}:{review:Review;paperId:number}){const isDraft=review.status==='DRAFT';const f=useForm({summary:review.summary||'',recommendation:review.recommendation||'ACCEPT'});const cf=useForm({body:'',page:''});const submit=(e:FormEvent)=>{e.preventDefault();f.patch(`/reviews/${review.id}`)};const addComment=(e:FormEvent)=>{e.preventDefault();cf.post(`/reviews/${review.id}/comments`,{onSuccess:()=>cf.reset()})};if(isDraft){return <Card className="p-5 border-teal-200"><h3 className="font-semibold text-teal-900 mb-4">Submit your review</h3><form onSubmit={submit} className="space-y-4"><label className="block"><span className="text-sm font-semibold mb-1 block">Recommendation</span><select required className="field" value={f.data.recommendation} onChange={e=>f.setData('recommendation',e.target.value)}><option value="ACCEPT">Accept</option><option value="MINOR_REVISION">Minor Revision</option><option value="MAJOR_REVISION">Major Revision</option><option value="REJECT">Reject</option></select></label><label className="block"><span className="text-sm font-semibold mb-1 block">Summary</span><textarea required className="field min-h-[100px]" value={f.data.summary} onChange={e=>f.setData('summary',e.target.value)} placeholder="Provide your review summary..."/></label><button className="btn-primary" disabled={f.processing}>Submit Review</button></form></Card>}return <Card className="p-5"><div className="flex justify-between"><h3 className="font-semibold">{review.reviewer?.name||'Reviewer'}</h3><span className="status status-neutral">{review.recommendation||review.status}</span></div><p className="mt-3 text-sm leading-6 text-slate-600">{review.summary||'No summary provided.'}</p>{review.comments&&review.comments.length>0&&<div className="mt-4 space-y-2 border-t pt-3">{review.comments.map((c:any,i:number)=><div key={c.id??i} className="text-sm"><strong className="text-slate-800">{c.user?.name||'User'}</strong>{c.page&&<span className="ml-1 text-xs text-slate-400">p.{c.page}</span>}<p className="text-slate-600">{c.body}</p></div>)}</div>}<form onSubmit={addComment} className="mt-4 flex gap-2 border-t pt-3"><input className="field flex-1 text-sm" placeholder="Add a comment..." value={cf.data.body} onChange={e=>cf.setData('body',e.target.value)} required/><input className="field w-16 text-sm" placeholder="Page" type="number" min="1" value={cf.data.page} onChange={e=>cf.setData('page',e.target.value)}/><button className="btn-secondary text-sm" disabled={cf.processing}>Comment</button></form></Card>}
function EvidenceList({rows=[]}:{rows?:Evidence[]}){return rows.length?<div className="mt-4 border-l-2 border-teal-200 pl-4">{rows.map((e,i)=><p key={i} className="text-xs leading-5 text-slate-500"><strong>{e.section||'Evidence'}{e.page?` · p. ${e.page}`:''}</strong>{e.excerpt?` — “${e.excerpt}”`:''}</p>)}</div>:null}
function BoxEmpty({what}:{what:string}){return <Card><EmptyState title={`No ${what} available`} description="This section stays empty until Laravel returns persisted results. Nothing is generated in the browser."/></Card>}
