import { Card, EmptyState, PageHeader, ProcessingState, StatusBadge, Tabs } from '@/Components/UI';
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import type { Evidence, Finding, Paper, Reference, Review, Score } from '@/types';
import { displayDate } from '@/lib/contracts';
import { Head, Link, router, useForm } from '@inertiajs/react';
import { Download, ExternalLink, MessageSquareText, Send } from 'lucide-react';
import { FormEvent } from 'react';
const tabs=[['overview','Overview'],['analysis','Analysis'],['scores','Scores'],['findings','Findings'],['references','References'],['reviewer','AI Reviewer'],['qa','Q&A'],['reviews','Reviews']].map(([id,label])=>({id,label}));
type Props={paper:Paper;tab?:string;analysis?:Record<string,unknown>|null;scores?:Score[];findings?:Finding[];references?:Reference[];aiReview?:Review|null;reviews?:Review[];questions?:Array<{id?:number;question:string;answer?:string|null;found?:boolean;evidence?:Evidence[]}>;can?:{download?:boolean;review?:boolean;ask?:boolean;retry?:boolean}};
export default function Show(p:Props){const active=p.tab??new URLSearchParams(window.location.search).get('tab')??'overview';return <AuthenticatedLayout><Head title={p.paper.title}/><div className="page-wrap"><PageHeader eyebrow="Paper workspace" title={p.paper.title} description={[p.paper.authors?.map(a=>a.name).join(', '),p.paper.journal,p.paper.publication_year].filter(Boolean).join(' · ')||'Publication metadata not provided'} actions={<>{p.can?.download&&<a href={`/papers/${p.paper.id}/download`} className="btn-secondary"><Download className="h-4 w-4"/>PDF</a>}<StatusBadge status={p.paper.status}/></>}/><ProcessingState status={p.paper.status} error={p.paper.error_message}/><div className="mt-6"><Tabs items={tabs} active={active} baseUrl={`/papers/${p.paper.id}`}/>{active==='overview'&&<Overview {...p}/>} {active==='analysis'&&<Analysis value={p.analysis}/>} {active==='scores'&&<Scores rows={p.scores}/>} {active==='findings'&&<Findings rows={p.findings}/>} {active==='references'&&<References rows={p.references}/>} {active==='reviewer'&&<ReviewView review={p.aiReview}/>} {active==='qa'&&<Qa {...p}/>} {active==='reviews'&&<Reviews rows={p.reviews}/>}</div></div></AuthenticatedLayout>}
function Overview({paper,analysis}:{paper:Paper;analysis?:Record<string,unknown>|null}){return <div className="grid gap-6 lg:grid-cols-[1.5fr_.5fr]"><Card className="p-6"><h2 className="text-lg font-semibold">Abstract</h2><p className="mt-3 whitespace-pre-line text-sm leading-7 text-slate-600">{paper.abstract||'No abstract was provided.'}</p></Card><Card className="p-6"><h2 className="font-semibold">Metadata</h2><dl className="mt-4 space-y-4 text-sm"><Meta k="DOI" v={paper.doi}/><Meta k="Journal" v={paper.journal}/><Meta k="Year" v={paper.publication_year}/><Meta k="Uploaded" v={displayDate(paper.created_at)}/><Meta k="Domain" v={String(analysis?.research_domain??'—')}/></dl></Card></div>}
function Meta({k,v}:{k:string;v:unknown}){return <div><dt className="text-xs font-semibold uppercase tracking-wide text-slate-400">{k}</dt><dd className="mt-1 break-words text-slate-700">{v==null||v===''?'—':String(v)}</dd></div>}
function Analysis({value}:{value?:Record<string,unknown>|null}){if(!value)return <BoxEmpty what="analysis"/>;const entries=Object.entries(value).filter(([,v])=>v!=null);return <div className="grid gap-4 md:grid-cols-2">{entries.map(([k,v])=><Card key={k} className="p-5"><h3 className="font-semibold capitalize">{k.replaceAll('_',' ')}</h3><div className="mt-3 text-sm leading-6 text-slate-600">{render(v)}</div></Card>)}</div>}
const render=(v:unknown):React.ReactNode=>Array.isArray(v)?<ul className="list-disc space-y-1 pl-5">{v.map((x,i)=><li key={i}>{typeof x==='object'?JSON.stringify(x):String(x)}</li>)}</ul>:typeof v==='object'?<dl className="space-y-2">{Object.entries(v as Record<string,unknown>).map(([k,x])=><div key={k}><dt className="font-medium capitalize text-slate-800">{k.replaceAll('_',' ')}</dt><dd>{Array.isArray(x)?x.join(', '):String(x??'—')}</dd></div>)}</dl>:String(v);
function Scores({rows=[]}:{rows?:Score[]}){return rows.length?<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{rows.map((s,i)=><Card key={s.id??i} className="p-5"><div className="flex justify-between"><h3 className="font-semibold capitalize">{s.criterion.replaceAll('_',' ')}</h3><strong className="text-2xl text-teal-700">{s.score}<span className="text-sm text-slate-400">/100</span></strong></div><div className="mt-3 h-2 rounded bg-slate-100"><div className="h-2 rounded bg-teal-600" style={{width:`${Math.min(100,Math.max(0,s.score))}%`}}/></div><p className="mt-4 text-sm leading-6 text-slate-600">{s.reason||'No scoring rationale returned.'}</p></Card>)}</div>:<BoxEmpty what="scores"/>}
function Findings({rows=[]}:{rows?:Finding[]}){return rows.length?<div className="space-y-4">{rows.map((f,i)=><Card key={f.id??i} className="p-5"><div className="flex flex-wrap items-center gap-2"><span className={`status ${['high','critical'].includes(f.severity?.toLowerCase()??'')?'status-danger':'status-warning'}`}>{f.severity||'Unrated'}</span><span className="text-xs font-semibold uppercase text-slate-400">{f.category}</span></div><h3 className="mt-3 font-semibold">{f.finding||f.title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{f.explanation}</p><EvidenceList rows={f.evidence}/></Card>)}</div>:<BoxEmpty what="findings"/>}
function References({rows=[]}:{rows?:Reference[]}){return rows.length?<Card className="divide-y divide-slate-100">{rows.map((r,i)=><div className="p-5" key={r.id??i}><p className="text-sm leading-6">{r.citation||[r.authors,r.title,r.year].filter(Boolean).join('. ')}</p>{r.cited_in_text!=null&&<p className="mt-2 text-xs text-slate-500">{r.cited_in_text?'Observed in text':'Not observed in text'}</p>}</div>)}</Card>:<BoxEmpty what="references"/>}
function ReviewView({review}:{review?:Review|null}){return review?<div className="space-y-4"><Card className="p-6"><div className="flex flex-wrap justify-between gap-3"><h2 className="text-lg font-semibold">Reviewer report</h2><span className="status status-info">{review.recommendation?.replaceAll('_',' ')||'No recommendation'}</span></div><p className="mt-4 text-sm leading-7 text-slate-600">{review.summary}</p></Card>{[['Strengths',review.strengths],['Major concerns',review.major_concerns],['Minor concerns',review.minor_concerns]].map(([title,items])=><Card key={String(title)} className="p-5"><h3 className="font-semibold">{String(title)}</h3>{Array.isArray(items)&&items.length?<ul className="mt-3 list-disc space-y-2 pl-5 text-sm text-slate-600">{items.map((x,i)=><li key={i}>{x}</li>)}</ul>:<p className="mt-2 text-sm text-slate-500">None returned.</p>}</Card>)}</div>:<BoxEmpty what="AI reviewer report"/>}
function Qa(p:Props){const f=useForm({question:''});const submit=(e:FormEvent)=>{e.preventDefault();f.post(`/papers/${p.paper.id}/questions`,{onSuccess:()=>f.reset()})};return <div className="space-y-5"><Card className="p-5"><form onSubmit={submit}><label htmlFor="question" className="font-semibold">Ask about this paper</label><p className="mt-1 text-sm text-slate-500">Answers are grounded only in the selected paper and include evidence when available.</p><div className="mt-4 flex flex-col gap-2 sm:flex-row"><input id="question" required className="field flex-1" value={f.data.question} onChange={e=>f.setData('question',e.target.value)} placeholder="What methodology does the paper use?"/><button disabled={f.processing||!p.can?.ask} className="btn-primary"><Send className="h-4 w-4"/>Ask</button></div>{f.errors.question&&<p className="mt-2 text-sm text-rose-600">{f.errors.question}</p>}</form></Card>{p.questions?.length?p.questions.map((q,i)=><Card key={q.id??i} className="p-5"><p className="font-semibold">{q.question}</p><p className="mt-3 text-sm leading-7 text-slate-600">{q.answer||'Awaiting an answer.'}</p><EvidenceList rows={q.evidence}/></Card>):<BoxEmpty what="questions"/>}</div>}
function Reviews({rows=[]}:{rows?:Review[]}){return rows.length?<div className="space-y-4">{rows.map((r,i)=><Card key={r.id??i} className="p-5"><div className="flex justify-between"><h3 className="font-semibold">{r.reviewer?.name||'Reviewer'}</h3><span className="status status-neutral">{r.status||'Draft'}</span></div><p className="mt-3 text-sm leading-6 text-slate-600">{r.summary||'No summary provided.'}</p></Card>)}</div>:<BoxEmpty what="reviews"/>}
function EvidenceList({rows=[]}:{rows?:Evidence[]}){return rows.length?<div className="mt-4 border-l-2 border-teal-200 pl-4">{rows.map((e,i)=><p key={i} className="text-xs leading-5 text-slate-500"><strong>{e.section||'Evidence'}{e.page?` · p. ${e.page}`:''}</strong>{e.excerpt?` — “${e.excerpt}”`:''}</p>)}</div>:null}
function BoxEmpty({what}:{what:string}){return <Card><EmptyState title={`No ${what} available`} description="This section stays empty until Laravel returns persisted results. Nothing is generated in the browser."/></Card>}
