<?php
use Illuminate\Database\Migrations\Migration; use Illuminate\Database\Schema\Blueprint; use Illuminate\Support\Facades\Schema;
return new class extends Migration { public function up():void {
Schema::create('roles',fn(Blueprint $t)=>[$t->id(),$t->string('name')->unique(),$t->timestamps()]);
Schema::create('role_user',fn(Blueprint $t)=>[$t->foreignId('role_id')->constrained()->cascadeOnDelete(),$t->foreignId('user_id')->constrained()->cascadeOnDelete(),$t->primary(['role_id','user_id'])]);
Schema::create('papers',function(Blueprint $t){$t->id();$t->string('title');$t->text('abstract')->nullable();$t->unsignedSmallInteger('publication_year')->nullable();$t->string('journal')->nullable();$t->string('doi')->nullable()->unique();$t->json('keywords')->nullable();$t->string('file_path');$t->string('status')->index();$t->foreignId('uploaded_by')->constrained('users')->restrictOnDelete();$t->timestamps();});
Schema::create('paper_authors',function(Blueprint $t){$t->id();$t->foreignId('paper_id')->constrained()->cascadeOnDelete();$t->string('name');$t->string('affiliation')->nullable();$t->unsignedInteger('position');$t->timestamps();$t->unique(['paper_id','position']);});
Schema::create('paper_sections',function(Blueprint $t){$t->id();$t->foreignId('paper_id')->constrained()->cascadeOnDelete();$t->string('heading');$t->longText('content');$t->unsignedInteger('page_start')->nullable();$t->unsignedInteger('page_end')->nullable();$t->string('chunk_id')->nullable()->index();$t->timestamps();});
Schema::create('paper_analyses',function(Blueprint $t){$t->id();$t->foreignId('paper_id')->constrained()->cascadeOnDelete();$t->string('paper_type')->nullable();$t->string('research_domain')->nullable();$t->text('summary')->nullable();$t->json('structure')->nullable();$t->json('methodology')->nullable();$t->json('keywords')->nullable();$t->timestamps();});
Schema::create('paper_scores',function(Blueprint $t){$t->id();$t->foreignId('paper_analysis_id')->constrained()->cascadeOnDelete();$t->string('criterion');$t->unsignedTinyInteger('score');$t->text('reason');$t->json('evidence')->nullable();$t->timestamps();$t->unique(['paper_analysis_id','criterion']);});
Schema::create('paper_findings',function(Blueprint $t){$t->id();$t->foreignId('paper_analysis_id')->constrained()->cascadeOnDelete();$t->string('severity');$t->string('category');$t->text('finding');$t->text('explanation')->nullable();$t->decimal('confidence',4,3)->nullable();$t->json('evidence')->nullable();$t->timestamps();});
Schema::create('paper_references',function(Blueprint $t){$t->id();$t->foreignId('paper_id')->constrained()->cascadeOnDelete();$t->text('raw_text');$t->string('citation_key')->nullable()->index();$t->unsignedSmallInteger('publication_year')->nullable();$t->boolean('cited_in_text')->default(false);$t->timestamps();});
Schema::create('reviewer_assignments',function(Blueprint $t){$t->id();$t->foreignId('paper_id')->constrained()->cascadeOnDelete();$t->foreignId('reviewer_id')->constrained('users')->cascadeOnDelete();$t->foreignId('assigned_by')->constrained('users')->restrictOnDelete();$t->timestamp('assigned_at');$t->timestamps();$t->unique(['paper_id','reviewer_id']);});
Schema::create('reviews',function(Blueprint $t){$t->id();$t->foreignId('paper_id')->constrained()->cascadeOnDelete();$t->foreignId('reviewer_id')->constrained('users')->cascadeOnDelete();$t->string('status')->default('DRAFT');$t->string('recommendation')->nullable();$t->text('summary')->nullable();$t->json('scores')->nullable();$t->timestamp('submitted_at')->nullable();$t->timestamps();$t->unique(['paper_id','reviewer_id']);});
Schema::create('review_comments',function(Blueprint $t){$t->id();$t->foreignId('review_id')->constrained()->cascadeOnDelete();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->text('body');$t->unsignedInteger('page')->nullable();$t->timestamps();});
Schema::create('ai_jobs',function(Blueprint $t){$t->id();$t->uuid('request_id')->unique();$t->foreignId('paper_id')->constrained()->cascadeOnDelete();$t->string('type');$t->string('status')->index();$t->unsignedTinyInteger('retry_count')->default(0);$t->text('error')->nullable();$t->timestamp('started_at')->nullable();$t->timestamp('completed_at')->nullable();$t->timestamps();});
Schema::create('ai_requests',function(Blueprint $t){$t->id();$t->foreignId('ai_job_id')->constrained()->cascadeOnDelete();$t->uuid('request_id')->index();$t->string('operation');$t->json('payload');$t->unsignedTinyInteger('attempt')->default(1);$t->timestamps();});
Schema::create('ai_responses',function(Blueprint $t){$t->id();$t->foreignId('ai_request_id')->constrained()->cascadeOnDelete();$t->boolean('success');$t->json('payload')->nullable();$t->string('error_code')->nullable();$t->text('error_message')->nullable();$t->unsignedInteger('duration_ms')->nullable();$t->timestamps();});
Schema::create('audit_logs',function(Blueprint $t){$t->id();$t->foreignId('actor_id')->nullable()->constrained('users')->nullOnDelete();$t->string('action')->index();$t->nullableMorphs('target');$t->json('metadata')->nullable();$t->ipAddress('ip_address')->nullable();$t->timestamps();});
} public function down():void { foreach(['audit_logs','ai_responses','ai_requests','ai_jobs','review_comments','reviews','reviewer_assignments','paper_references','paper_findings','paper_scores','paper_analyses','paper_sections','paper_authors','papers','role_user','roles'] as $table) Schema::dropIfExists($table); }};
